# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ZI_GenerateAlphaMNMetro <- function(Par, Y, Z, Covar, propsigma, priormu, priorSigmas) {
    .Call(`_ZIPBayes_ZI_GenerateAlphaMNMetro`, Par, Y, Z, Covar, propsigma, priormu, priorSigmas)
}

ZI_GenerateBetaMetro <- function(Par, U, Covar, propsigma, priorgamma) {
    .Call(`_ZIPBayes_ZI_GenerateBetaMetro`, Par, U, Covar, propsigma, priorgamma)
}

ZI_GenerateBigJoint <- function(Yistar, Ui1bound, Ui2bound, mu1i, mu2i, muZplusi, muZminusi) {
    .Call(`_ZIPBayes_ZI_GenerateBigJoint`, Yistar, Ui1bound, Ui2bound, mu1i, mu2i, muZplusi, muZminusi)
}

ZI_GenerateJoint <- function(Yistar, minusbound, phii, mu2i, muZplusi, muZminusi) {
    .Call(`_ZIPBayes_ZI_GenerateJoint`, Yistar, minusbound, phii, mu2i, muZplusi, muZminusi)
}

ZI_GeneratePoiPar_Binary <- function(Par, covariates, Outcome, priorgamma) {
    .Call(`_ZIPBayes_ZI_GeneratePoiPar_Binary`, Par, covariates, Outcome, priorgamma)
}

ZI_GenerateU1 <- function(Y, U2, mu1) {
    .Call(`_ZIPBayes_ZI_GenerateU1`, Y, U2, mu1)
}

ZI_GenerateU2 <- function(Y, U1, mu2) {
    .Call(`_ZIPBayes_ZI_GenerateU2`, Y, U1, mu2)
}

ZI_GenerateV <- function(Y, Zminus, muZminus, covminus) {
    .Call(`_ZIPBayes_ZI_GenerateV`, Y, Zminus, muZminus, covminus)
}

ZI_GenerateZpZmJoint <- function(Yistar, Yi, muZplusi, muZminusi) {
    .Call(`_ZIPBayes_ZI_GenerateZpZmJoint`, Yistar, Yi, muZplusi, muZminusi)
}

